modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="cursesandstuff"
version="0.0.1"
displayName="CurseCraft"
credits="DISCLAIMER: All concepts/abilities used are from Jujistu Kaisen, by Gege Akutami. I DO NOT OWN ANYTHING TAKEN FROM JUJISTU KAISEN"
displayURL="https://mcreator.net"
authors="Ghostx10"
description="Adds cursed techniques and more from Jujitsu Kaisen!"

[[dependencies.cursesandstuff]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"




